// This file contains mock data for demonstration purposes
// In a real application, this would come from your backend API

export const mockMetrics = {
  totalProducts: 15234,
  totalStores: 1847,
  costSavings: 2800000,
  forecastAccuracy: 94.2,
};

export const mockAlerts = [
  {
    id: 1,
    type: "stockout",
    title: "Stockout Alert",
    message: "iPhone 15 Pro expected stockout at Store #2847 in 2 days",
    severity: "high",
    productId: 1,
    storeId: 1,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 2,
    type: "overstock",
    title: "Overstock Warning",
    message: "Winter Jackets category showing 40% overstock in Northeast region",
    severity: "medium",
    productId: null,
    storeId: null,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: 3,
    type: "optimal",
    title: "Optimal Stock Level",
    message: "Gaming Consoles maintaining perfect stock balance across all stores",
    severity: "low",
    productId: null,
    storeId: null,
    isActive: true,
    createdAt: new Date(),
  },
];

export const mockProducts = [
  {
    id: 1,
    sku: "SKU-001847",
    name: "iPhone 15 Pro 256GB",
    category: "Electronics",
    currentStock: 23,
    predictedDemand: 45,
    recommendedReorder: 50,
    priority: "high",
    daysUntilStockout: 2,
    createdAt: new Date(),
  },
  {
    id: 2,
    sku: "SKU-002193",
    name: "Samsung 65\" QLED TV",
    category: "Electronics",
    currentStock: 8,
    predictedDemand: 12,
    recommendedReorder: 15,
    priority: "medium",
    daysUntilStockout: 5,
    createdAt: new Date(),
  },
  {
    id: 3,
    sku: "SKU-003456",
    name: "Nike Air Max 270",
    category: "Clothing",
    currentStock: 156,
    predictedDemand: 89,
    recommendedReorder: 100,
    priority: "low",
    daysUntilStockout: 14,
    createdAt: new Date(),
  },
  {
    id: 4,
    sku: "SKU-004789",
    name: "Dyson V15 Vacuum",
    category: "Home & Garden",
    currentStock: 34,
    predictedDemand: 67,
    recommendedReorder: 75,
    priority: "high",
    daysUntilStockout: 3,
    createdAt: new Date(),
  },
];

export const mockStores = [
  {
    id: 1,
    storeId: "STORE-001",
    name: "WalCart NYC",
    city: "New York",
    region: "Northeast",
    demandLevel: "high",
    createdAt: new Date(),
  },
  {
    id: 2,
    storeId: "STORE-002",
    name: "WalCart LA",
    city: "Los Angeles",
    region: "West",
    demandLevel: "very_high",
    createdAt: new Date(),
  },
  {
    id: 3,
    storeId: "STORE-003",
    name: "WalCart Chicago",
    city: "Chicago",
    region: "Midwest",
    demandLevel: "medium",
    createdAt: new Date(),
  },
  {
    id: 4,
    storeId: "STORE-004",
    name: "WalCart Houston",
    city: "Houston",
    region: "South",
    demandLevel: "high",
    createdAt: new Date(),
  },
  {
    id: 5,
    storeId: "STORE-005",
    name: "WalCart Phoenix",
    city: "Phoenix",
    region: "West",
    demandLevel: "medium",
    createdAt: new Date(),
  },
  {
    id: 6,
    storeId: "STORE-006",
    name: "WalCart Philadelphia",
    city: "Philadelphia",
    region: "Northeast",
    demandLevel: "medium",
    createdAt: new Date(),
  },
  {
    id: 7,
    storeId: "STORE-007",
    name: "WalCart San Antonio",
    city: "San Antonio",
    region: "South",
    demandLevel: "medium",
    createdAt: new Date(),
  },
  {
    id: 8,
    storeId: "STORE-008",
    name: "WalCart Dallas",
    city: "Dallas",
    region: "South",
    demandLevel: "high",
    createdAt: new Date(),
  },
];

export const mockForecastData = [
  { day: "Day 1", predicted: 45, actual: 42 },
  { day: "Day 2", predicted: 52, actual: 48 },
  { day: "Day 3", predicted: 48, actual: 51 },
  { day: "Day 4", predicted: 61, actual: 58 },
  { day: "Day 5", predicted: 55, actual: 52 },
  { day: "Day 6", predicted: 67, actual: 65 },
  { day: "Day 7", predicted: 59, actual: null },
];

export const mockChatbotResponses = {
  stock: "Current stock levels show 23 units of iPhone 15 Pro. We recommend reordering 50 units within 2 days to avoid stockout.",
  forecast: "Our AI forecast shows 94.2% accuracy. Next week's demand is expected to increase by 15% in electronics category.",
  alert: "There are 3 active alerts: 1 stockout warning, 1 overstock alert, and 1 optimal stock notification.",
  savings: "Our smart inventory system has saved $2.8M this quarter through optimized stock management and reduced waste.",
  stores: "We currently monitor 1,847 stores across different regions. The highest demand is in our West Coast locations.",
  default: "I can help you with that! Let me check our inventory data...",
};
